//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComShopEntities : DbContext
    {
        public ComShopEntities()
            : base("name=ComShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_Bill> P_Bill { get; set; }
        public virtual DbSet<P_Bill_items> P_Bill_items { get; set; }
        public virtual DbSet<P_Department> P_Department { get; set; }
        public virtual DbSet<P_Employee> P_Employee { get; set; }
        public virtual DbSet<P_Member> P_Member { get; set; }
        public virtual DbSet<P_Product> P_Product { get; set; }
        public virtual DbSet<P_Promotion> P_Promotion { get; set; }
    }
}
