//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_Bill()
        {
            this.P_Bill_items = new HashSet<P_Bill_items>();
        }
    
        public string bill_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<double> sum_price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Bill_items> P_Bill_items { get; set; }
        public virtual P_Member P_Member { get; set; }
    }
}
