//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Bill_items
    {
        public int item_id { get; set; }
        public string bill_id { get; set; }
        public string product_id { get; set; }
        public int amount { get; set; }
        public double sum_price { get; set; }
    
        public virtual P_Bill P_Bill { get; set; }
        public virtual P_Product P_Product { get; set; }
    }
}
