//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_phone { get; set; }
        public string emp_username { get; set; }
        public string emp_password { get; set; }
        public Nullable<int> depart_id { get; set; }
    
        public virtual P_Department P_Department { get; set; }
    }
}
