//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APD_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_Product()
        {
            this.P_Bill_items = new HashSet<P_Bill_items>();
            this.P_Promotion = new HashSet<P_Promotion>();
            this.P_Promotion1 = new HashSet<P_Promotion>();
        }
    
        public string p_id { get; set; }
        public string p_name { get; set; }
        public string p_detail { get; set; }
        public string p_image { get; set; }
        public double p_price { get; set; }
        public int p_amount { get; set; }
        public string p_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Bill_items> P_Bill_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Promotion> P_Promotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Promotion> P_Promotion1 { get; set; }
    }
}
